FROM debian:stable-slim

# Installer utilitaires
RUN apt-get update && apt-get install -y \
    frr frr-pythontools iproute2 net-tools busybox \
    && rm -rf /var/lib/apt/lists/*

# Activer les démons nécessaires
COPY config/daemons /etc/frr/daemons
COPY config/*.conf /etc/frr/
COPY startup.sh /startup.sh

# Donner les droits d'exécution
RUN chmod +x /startup.sh

CMD ["/startup.sh"]
